### ISSUE TITLE
Integration into Asio

### ISSUE THREAD

**Issue by pfeatherstone** [klemens-morgenstern/async#1]
Is the plan to merge into Asio ? Also, thanks for this! Library coroutines couldn't come sooner :)

**Comment by klemens-morgenstern** [comment]
I don't think that this will be accepted into asio. I hope to submit it to boost soon.

**Comment by klemens-morgenstern** [comment]
@pfeatherstone I think this library is relatively stable now, while of course still experimental. 

I am looking for early users now.
