### ISSUE TITLE
More documentation for interruption is required

### ISSUE THREAD

**Issue by akrzemi1** [klemens-morgenstern/async#120]
The notions of "interrupt", "cancel" and "detach" are not documented enough. After reading the doc, I do not know how I should use interuption and if I even should use it.

I read in one place that an interruption causes not completed awaitables to be detached. Can I detach a `promise` or a `generator` this way? But I see nothing on the `generator`'s or `promise`'s documentation to confirm it. 

Do I have to do anything in my coroutine to enable the interruption?

HOw is cancellation different?

**Comment by klemens-morgenstern** [comment]
Interrupt is akin to a semi-public implementation detail. It's meant to make select work lossless.

What gets detached is the co_await itself, not the awaited thing.
