### ISSUE TITLE
The Echo Server example issue

### ISSUE THREAD

**Issue by akrzemi1** [klemens-morgenstern/async#121]
When I try the echo server example on MSVC, it echoes every letter separately: I want to type (form terminal, using telnet) a word, but upon every single letter it echoes that letter alone. So I get 

```
wwoorrlldd


```
instead of

```
world
world
```

Is that intentional? I recall that the coroutine example from ASIO worked as I expect.

**Comment by klemens-morgenstern** [comment]
Not intentional, but correct if you use telnet. The echo server just sends back the packages you sent, so if telnet sends them individually, that's correct.

**Comment by akrzemi1** [comment]
Thanks.
