### ISSUE TITLE
[feature] .then() method for promise

### ISSUE THREAD

**Issue by jsaf0** [klemens-morgenstern/async#6]
Being able to attach a callback to the `promise` type which detaches the promise and gets called when done (given an exception_ptr and the return value) would allow the user to use the `promise` type in non-coroutine code in traditional async callback fashion, and allow one to use the `promise` type as a generic handle for async results.

Example usage:
```
async::promise<int> foo()
{
    co_return 1;
}
```

```
foo().then([](std::exception_ptr, int) {
    // Do something with I
});
```

This is similar to `Promise.prototype.then()` in JS.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

**Comment by klemens-morgenstern** [comment]
What's the use case if I may ask?

**Comment by klemens-morgenstern** [comment]
That is to say, you can `spawn` a task and use universal asio completion already. 

```cpp
async::task<int> foo()
{
    co_return 1;
}

spawn(foo(), [](std::exception_ptr e, int i) {... });
```

Which is cleaner & consistent with asio, so I'd need to know what you want. The problem with doing that with a promise is that the global executor might be a pitfall for many new users, which is not a problem with `task`s.

**Comment by klemens-morgenstern** [comment]
Implementation wise, this cannot avoid allocations. So you might as well write your own:

```cpp
template<async::awaitable ToAwait, typename Success, typename Error>
async::detachedthen(ToAwait && aw, Success && onSucces, Error && onError(
try {
   onSuccess(co_await std::forward<ToAwait>(aw));
} 
catch (...)
{
   onError(std::current_exception());
}
```

More generic and pretty much what a `then` member function would do.

**Comment by klemens-morgenstern** [comment]
@jsaf0 Does that solve the issue?
