### ISSUE TITLE
co_main hangs for long-running, detached tasks

### ISSUE THREAD

**Issue by anarthal** [klemens-morgenstern/async#72]
If you spawn a long-running, detached task (like a websocket session), SIGINT won't cancel it, but `co_main` will wait for it, causing a deadlock.

**Comment by anarthal** [comment]
It's detached, so, no.

**Comment by anarthal** [comment]
But `co_main` *does* wait for all tasks to finish, detached or not. That's calling for deadlocks.

**Comment by klemens-morgenstern** [comment]
I'll check if I can wire up detached tasks to a global cancellation thing so they can get signalled.

My idea was that you don't detach, but use wait_group et al.

**Comment by klemens-morgenstern** [comment]
I think the approach is correct. It's akin to a `main` creating & detaching threads, which won't be stopped.
