### ISSUE TITLE
Dependency on boost/smart_ptr

### ISSUE THREAD

**Issue by anarthal** [klemens-morgenstern/async#78]
Just used for allocate_unique, which seems a pretty trivial function - is it really worth it?

**Comment by klemens-morgenstern** [comment]
I don't know - this is supposed to be a boost library, why is this dependency bad?

**Comment by anarthal** [comment]
It makes the vcpkg package require an extra dependency, for instance. Although I guess depending on Asio might be already pulling it, so this may have no relevance.
