### ISSUE TITLE
BOOST_ASYNC_NO_PMR

### ISSUE THREAD

**Issue by anarthal** [klemens-morgenstern/async#79]
There seems to be no docs or testing regarding this macro.

**Comment by klemens-morgenstern** [comment]
Yeah that shouldn't being develop or master. Shouldn't hurt anyone though. 

The idea is to allow disabling all the PMR stuff, but I didn't complete it yet.

**Comment by klemens-morgenstern** [comment]
I tried to, but the select/gather/join impl relies on pmr. So pmr will be removed.
