### ISSUE TITLE
Docs: word "task" in description of `wait_group`

### ISSUE THREAD

**Issue by akrzemi1** [klemens-morgenstern/async#94]
The description of `wait_group`
https://github.com/klemens-morgenstern/async/blob/develop/doc/reference/wait_group.adoc
says it only works with `promise<void>` but it mentions the processing of "tasks". It is confusing, as the `task` is a different type in this library. 
Second, why does `wait_group` not work with `task<void>`? The first intuition is that `promise` and `type` only differ by the initial suspend.

**Comment by klemens-morgenstern** [comment]
Well it needs to pick something so that I can put it in a vector.  Wrapping a task in a promise is a simple lambda.

**Comment by akrzemi1** [comment]
This looks like another argument in favour of keeping tasks and promisses in the same type.

How does one convert a task into a promise with a lambda? Is there a conversion function, or do I need a yet another coroutine?

Or maybe you need some type-erasure 8n order to be able to store either?

**Comment by klemens-morgenstern** [comment]
```cpp
[]<typename T>(task<T> t) -> promise<T> {co_return co_await t;}
```

Yes, you need another coro to wrap it.

**Comment by akrzemi1** [comment]
Maybe provide a function that converts a `task` to a promise?

**Comment by klemens-morgenstern** [comment]
What is the use case?

**Comment by akrzemi1** [comment]
When I need to a `task<>` into a `wait_group`. 
I personally never had a need to do it. But this is my first exposure to this library, and it seems to me from this conversation that someone might want to use it.
